ARG GO_VERSION=1.22.4
FROM lib.matador.ais.co.th/golang:${GO_VERSION} AS builder

ENV GOPROXY=https://lib.matador.ais.co.th/repository/go,direct
ENV GONOSUMDB=lib.matador.ais.co.th
ENV GOPRIVATE=lib.matador.ais.co.th

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN go mod download
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o main ./cmd

FROM lib.matador.ais.co.th/alpine:latest
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app .
ENV TZ=Asia/Bangkok

EXPOSE 3000
CMD ["/app/main"]